import 'dart:convert';
import 'dart:io';
import 'package:http/http.dart' as http;

Future<void> main() async {
  print('Fetching Indonesian Regions...');

  const baseUrl = 'https://www.emsifa.com/api-wilayah-indonesia/api';
  final outputFile = File('lib/core/constants/regions_data.dart');

  try {
    // 1. Fetch Provinces
    final provResponse = await http.get(Uri.parse('$baseUrl/provinces.json'));
    if (provResponse.statusCode != 200)
      throw Exception('Failed to fetch provinces');

    final List<dynamic> provinces = json.decode(provResponse.body);
    final List<Map<String, String>> consolidatedData = [];

    print('Found ${provinces.length} provinces. Fetching regencies...');

    // 2. Fetch Regencies for each Province
    for (var prov in provinces) {
      final provId = prov['id'];
      final provName = _toTitleCase(prov['name']);

      final regResponse = await http.get(
        Uri.parse('$baseUrl/regencies/$provId.json'),
      );
      if (regResponse.statusCode == 200) {
        final List<dynamic> regencies = json.decode(regResponse.body);

        for (var reg in regencies) {
          final regName = _toTitleCase(reg['name']);
          // Format: "Province, City" as requested by user
          // User asked for: "Sulawesi tengah, Kota Palu"
          // We will store individual fields too just in case, but search will be on the combination
          consolidatedData.add({
            'province': provName,
            'city': regName,
            'label': '$provName, $regName',
          });
        }
      }
      stdout.write('.'); // Progress indicator
    }
    print('\nDone! Fetched ${consolidatedData.length} locations.');

    // 3. Write to Dart file
    final content = StringBuffer();
    content.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
    content.writeln('// Generated by tool/fetch_regions.dart');
    content.writeln('');
    content.writeln('const List<Map<String, String>> kIndonesianRegions = [');

    for (var item in consolidatedData) {
      content.writeln(
        "  {'province': '${_escape(item['province']!)}', 'city': '${_escape(item['city']!)}', 'label': '${_escape(item['label']!)}'},",
      );
    }

    content.writeln('];');

    await outputFile.writeAsString(content.toString());
    print('Successfully generated ${outputFile.path}');
  } catch (e) {
    print('Error: $e');
    exit(1);
  }
}

String _toTitleCase(String text) {
  if (text.isEmpty) return text;
  return text
      .split(' ')
      .map((word) {
        if (word.isEmpty) return word;
        return word[0].toUpperCase() + word.substring(1).toLowerCase();
      })
      .join(' ');
}

String _escape(String text) {
  return text.replaceAll("'", "\\'");
}
