import 'dart:convert';
import 'dart:io';
import 'package:http/http.dart' as http;

Future<void> main() async {
  print('Fetching Indonesian Universities...');

  const url = 'http://universities.hipolabs.com/search?country=Indonesia';
  final outputFile = File('lib/core/constants/universities_data.dart');

  try {
    final response = await http.get(Uri.parse(url));
    if (response.statusCode != 200)
      throw Exception('Failed to fetch universities');

    final List<dynamic> data = json.decode(response.body);
    final Set<String> uniqueUniversities = {};

    print('Found ${data.length} entries. Processing...');

    for (var item in data) {
      final name = item['name'] as String;
      // Clean up name if needed, but usually they are fine.
      // Maybe Title Case? Hipolabs usually has them formatted but let's be sure.
      uniqueUniversities.add(name);
    }

    final sortedUniversities = uniqueUniversities.toList()..sort();

    print('Unique universities: ${sortedUniversities.length}');

    // Write to Dart file
    final content = StringBuffer();
    content.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
    content.writeln('// Generated by tool/fetch_universities.dart');
    content.writeln('');
    content.writeln('const List<String> kUniversities = [');

    for (var name in sortedUniversities) {
      content.writeln("  '${_escape(name)}',");
    }

    content.writeln('];');

    await outputFile.writeAsString(content.toString());
    print('Successfully generated ${outputFile.path}');
  } catch (e) {
    print('Error: $e');
    exit(1);
  }
}

String _escape(String text) {
  return text.replaceAll("'", "\\'");
}
