// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/fetch_regions.dart

const List<Map<String, String>> kIndonesianRegions = [
  {
    'province': 'Aceh',
    'city': 'Kabupaten Simeulue',
    'label': 'Aceh, Kabupaten Simeulue',
  },
  {
    'province': 'Aceh',
    'city': 'Kabupaten Aceh Singkil',
    'label': 'Aceh, Kabupaten Aceh Singkil',
  },
  {
    'province': 'Aceh',
    'city': 'Kabupaten Aceh Selatan',
    'label': 'Aceh, Kabupaten Aceh Selatan',
  },
  {
    'province': 'Aceh',
    'city': 'Kabupaten Aceh Tenggara',
    'label': 'Aceh, Kabupaten Aceh Tenggara',
  },
  {
    'province': 'Aceh',
    'city': 'Kabupaten Aceh Timur',
    'label': 'Aceh, Kabupaten Aceh Timur',
  },
  {
    'province': 'Aceh',
    'city': 'Kabupaten Aceh Tengah',
    'label': 'Aceh, Kabupaten Aceh Tengah',
  },
  {
    'province': 'Aceh',
    'city': 'Kabupaten Aceh Barat',
    'label': 'Aceh, Kabupaten Aceh Barat',
  },
  {
    'province': 'Aceh',
    'city': 'Kabupaten Aceh Besar',
    'label': 'Aceh, Kabupaten Aceh Besar',
  },
  {
    'province': 'Aceh',
    'city': 'Kabupaten Pidie',
    'label': 'Aceh, Kabupaten Pidie',
  },
  {
    'province': 'Aceh',
    'city': 'Kabupaten Bireuen',
    'label': 'Aceh, Kabupaten Bireuen',
  },
  {
    'province': 'Aceh',
    'city': 'Kabupaten Aceh Utara',
    'label': 'Aceh, Kabupaten Aceh Utara',
  },
  {
    'province': 'Aceh',
    'city': 'Kabupaten Aceh Barat Daya',
    'label': 'Aceh, Kabupaten Aceh Barat Daya',
  },
  {
    'province': 'Aceh',
    'city': 'Kabupaten Gayo Lues',
    'label': 'Aceh, Kabupaten Gayo Lues',
  },
  {
    'province': 'Aceh',
    'city': 'Kabupaten Aceh Tamiang',
    'label': 'Aceh, Kabupaten Aceh Tamiang',
  },
  {
    'province': 'Aceh',
    'city': 'Kabupaten Nagan Raya',
    'label': 'Aceh, Kabupaten Nagan Raya',
  },
  {
    'province': 'Aceh',
    'city': 'Kabupaten Aceh Jaya',
    'label': 'Aceh, Kabupaten Aceh Jaya',
  },
  {
    'province': 'Aceh',
    'city': 'Kabupaten Bener Meriah',
    'label': 'Aceh, Kabupaten Bener Meriah',
  },
  {
    'province': 'Aceh',
    'city': 'Kabupaten Pidie Jaya',
    'label': 'Aceh, Kabupaten Pidie Jaya',
  },
  {
    'province': 'Aceh',
    'city': 'Kota Banda Aceh',
    'label': 'Aceh, Kota Banda Aceh',
  },
  {'province': 'Aceh', 'city': 'Kota Sabang', 'label': 'Aceh, Kota Sabang'},
  {'province': 'Aceh', 'city': 'Kota Langsa', 'label': 'Aceh, Kota Langsa'},
  {
    'province': 'Aceh',
    'city': 'Kota Lhokseumawe',
    'label': 'Aceh, Kota Lhokseumawe',
  },
  {
    'province': 'Aceh',
    'city': 'Kota Subulussalam',
    'label': 'Aceh, Kota Subulussalam',
  },
  {
    'province': 'Sumatera Utara',
    'city': 'Kabupaten Nias',
    'label': 'Sumatera Utara, Kabupaten Nias',
  },
  {
    'province': 'Sumatera Utara',
    'city': 'Kabupaten Mandailing Natal',
    'label': 'Sumatera Utara, Kabupaten Mandailing Natal',
  },
  {
    'province': 'Sumatera Utara',
    'city': 'Kabupaten Tapanuli Selatan',
    'label': 'Sumatera Utara, Kabupaten Tapanuli Selatan',
  },
  {
    'province': 'Sumatera Utara',
    'city': 'Kabupaten Tapanuli Tengah',
    'label': 'Sumatera Utara, Kabupaten Tapanuli Tengah',
  },
  {
    'province': 'Sumatera Utara',
    'city': 'Kabupaten Tapanuli Utara',
    'label': 'Sumatera Utara, Kabupaten Tapanuli Utara',
  },
  {
    'province': 'Sumatera Utara',
    'city': 'Kabupaten Toba Samosir',
    'label': 'Sumatera Utara, Kabupaten Toba Samosir',
  },
  {
    'province': 'Sumatera Utara',
    'city': 'Kabupaten Labuhan Batu',
    'label': 'Sumatera Utara, Kabupaten Labuhan Batu',
  },
  {
    'province': 'Sumatera Utara',
    'city': 'Kabupaten Asahan',
    'label': 'Sumatera Utara, Kabupaten Asahan',
  },
  {
    'province': 'Sumatera Utara',
    'city': 'Kabupaten Simalungun',
    'label': 'Sumatera Utara, Kabupaten Simalungun',
  },
  {
    'province': 'Sumatera Utara',
    'city': 'Kabupaten Dairi',
    'label': 'Sumatera Utara, Kabupaten Dairi',
  },
  {
    'province': 'Sumatera Utara',
    'city': 'Kabupaten Karo',
    'label': 'Sumatera Utara, Kabupaten Karo',
  },
  {
    'province': 'Sumatera Utara',
    'city': 'Kabupaten Deli Serdang',
    'label': 'Sumatera Utara, Kabupaten Deli Serdang',
  },
  {
    'province': 'Sumatera Utara',
    'city': 'Kabupaten Langkat',
    'label': 'Sumatera Utara, Kabupaten Langkat',
  },
  {
    'province': 'Sumatera Utara',
    'city': 'Kabupaten Nias Selatan',
    'label': 'Sumatera Utara, Kabupaten Nias Selatan',
  },
  {
    'province': 'Sumatera Utara',
    'city': 'Kabupaten Humbang Hasundutan',
    'label': 'Sumatera Utara, Kabupaten Humbang Hasundutan',
  },
  {
    'province': 'Sumatera Utara',
    'city': 'Kabupaten Pakpak Bharat',
    'label': 'Sumatera Utara, Kabupaten Pakpak Bharat',
  },
  {
    'province': 'Sumatera Utara',
    'city': 'Kabupaten Samosir',
    'label': 'Sumatera Utara, Kabupaten Samosir',
  },
  {
    'province': 'Sumatera Utara',
    'city': 'Kabupaten Serdang Bedagai',
    'label': 'Sumatera Utara, Kabupaten Serdang Bedagai',
  },
  {
    'province': 'Sumatera Utara',
    'city': 'Kabupaten Batu Bara',
    'label': 'Sumatera Utara, Kabupaten Batu Bara',
  },
  {
    'province': 'Sumatera Utara',
    'city': 'Kabupaten Padang Lawas Utara',
    'label': 'Sumatera Utara, Kabupaten Padang Lawas Utara',
  },
  {
    'province': 'Sumatera Utara',
    'city': 'Kabupaten Padang Lawas',
    'label': 'Sumatera Utara, Kabupaten Padang Lawas',
  },
  {
    'province': 'Sumatera Utara',
    'city': 'Kabupaten Labuhan Batu Selatan',
    'label': 'Sumatera Utara, Kabupaten Labuhan Batu Selatan',
  },
  {
    'province': 'Sumatera Utara',
    'city': 'Kabupaten Labuhan Batu Utara',
    'label': 'Sumatera Utara, Kabupaten Labuhan Batu Utara',
  },
  {
    'province': 'Sumatera Utara',
    'city': 'Kabupaten Nias Utara',
    'label': 'Sumatera Utara, Kabupaten Nias Utara',
  },
  {
    'province': 'Sumatera Utara',
    'city': 'Kabupaten Nias Barat',
    'label': 'Sumatera Utara, Kabupaten Nias Barat',
  },
  {
    'province': 'Sumatera Utara',
    'city': 'Kota Sibolga',
    'label': 'Sumatera Utara, Kota Sibolga',
  },
  {
    'province': 'Sumatera Utara',
    'city': 'Kota Tanjung Balai',
    'label': 'Sumatera Utara, Kota Tanjung Balai',
  },
  {
    'province': 'Sumatera Utara',
    'city': 'Kota Pematang Siantar',
    'label': 'Sumatera Utara, Kota Pematang Siantar',
  },
  {
    'province': 'Sumatera Utara',
    'city': 'Kota Tebing Tinggi',
    'label': 'Sumatera Utara, Kota Tebing Tinggi',
  },
  {
    'province': 'Sumatera Utara',
    'city': 'Kota Medan',
    'label': 'Sumatera Utara, Kota Medan',
  },
  {
    'province': 'Sumatera Utara',
    'city': 'Kota Binjai',
    'label': 'Sumatera Utara, Kota Binjai',
  },
  {
    'province': 'Sumatera Utara',
    'city': 'Kota Padangsidimpuan',
    'label': 'Sumatera Utara, Kota Padangsidimpuan',
  },
  {
    'province': 'Sumatera Utara',
    'city': 'Kota Gunungsitoli',
    'label': 'Sumatera Utara, Kota Gunungsitoli',
  },
  {
    'province': 'Sumatera Barat',
    'city': 'Kabupaten Kepulauan Mentawai',
    'label': 'Sumatera Barat, Kabupaten Kepulauan Mentawai',
  },
  {
    'province': 'Sumatera Barat',
    'city': 'Kabupaten Pesisir Selatan',
    'label': 'Sumatera Barat, Kabupaten Pesisir Selatan',
  },
  {
    'province': 'Sumatera Barat',
    'city': 'Kabupaten Solok',
    'label': 'Sumatera Barat, Kabupaten Solok',
  },
  {
    'province': 'Sumatera Barat',
    'city': 'Kabupaten Sijunjung',
    'label': 'Sumatera Barat, Kabupaten Sijunjung',
  },
  {
    'province': 'Sumatera Barat',
    'city': 'Kabupaten Tanah Datar',
    'label': 'Sumatera Barat, Kabupaten Tanah Datar',
  },
  {
    'province': 'Sumatera Barat',
    'city': 'Kabupaten Padang Pariaman',
    'label': 'Sumatera Barat, Kabupaten Padang Pariaman',
  },
  {
    'province': 'Sumatera Barat',
    'city': 'Kabupaten Agam',
    'label': 'Sumatera Barat, Kabupaten Agam',
  },
  {
    'province': 'Sumatera Barat',
    'city': 'Kabupaten Lima Puluh Kota',
    'label': 'Sumatera Barat, Kabupaten Lima Puluh Kota',
  },
  {
    'province': 'Sumatera Barat',
    'city': 'Kabupaten Pasaman',
    'label': 'Sumatera Barat, Kabupaten Pasaman',
  },
  {
    'province': 'Sumatera Barat',
    'city': 'Kabupaten Solok Selatan',
    'label': 'Sumatera Barat, Kabupaten Solok Selatan',
  },
  {
    'province': 'Sumatera Barat',
    'city': 'Kabupaten Dharmasraya',
    'label': 'Sumatera Barat, Kabupaten Dharmasraya',
  },
  {
    'province': 'Sumatera Barat',
    'city': 'Kabupaten Pasaman Barat',
    'label': 'Sumatera Barat, Kabupaten Pasaman Barat',
  },
  {
    'province': 'Sumatera Barat',
    'city': 'Kota Padang',
    'label': 'Sumatera Barat, Kota Padang',
  },
  {
    'province': 'Sumatera Barat',
    'city': 'Kota Solok',
    'label': 'Sumatera Barat, Kota Solok',
  },
  {
    'province': 'Sumatera Barat',
    'city': 'Kota Sawah Lunto',
    'label': 'Sumatera Barat, Kota Sawah Lunto',
  },
  {
    'province': 'Sumatera Barat',
    'city': 'Kota Padang Panjang',
    'label': 'Sumatera Barat, Kota Padang Panjang',
  },
  {
    'province': 'Sumatera Barat',
    'city': 'Kota Bukittinggi',
    'label': 'Sumatera Barat, Kota Bukittinggi',
  },
  {
    'province': 'Sumatera Barat',
    'city': 'Kota Payakumbuh',
    'label': 'Sumatera Barat, Kota Payakumbuh',
  },
  {
    'province': 'Sumatera Barat',
    'city': 'Kota Pariaman',
    'label': 'Sumatera Barat, Kota Pariaman',
  },
  {
    'province': 'Riau',
    'city': 'Kabupaten Kuantan Singingi',
    'label': 'Riau, Kabupaten Kuantan Singingi',
  },
  {
    'province': 'Riau',
    'city': 'Kabupaten Indragiri Hulu',
    'label': 'Riau, Kabupaten Indragiri Hulu',
  },
  {
    'province': 'Riau',
    'city': 'Kabupaten Indragiri Hilir',
    'label': 'Riau, Kabupaten Indragiri Hilir',
  },
  {
    'province': 'Riau',
    'city': 'Kabupaten Pelalawan',
    'label': 'Riau, Kabupaten Pelalawan',
  },
  {
    'province': 'Riau',
    'city': 'Kabupaten S I A K',
    'label': 'Riau, Kabupaten S I A K',
  },
  {
    'province': 'Riau',
    'city': 'Kabupaten Kampar',
    'label': 'Riau, Kabupaten Kampar',
  },
  {
    'province': 'Riau',
    'city': 'Kabupaten Rokan Hulu',
    'label': 'Riau, Kabupaten Rokan Hulu',
  },
  {
    'province': 'Riau',
    'city': 'Kabupaten Bengkalis',
    'label': 'Riau, Kabupaten Bengkalis',
  },
  {
    'province': 'Riau',
    'city': 'Kabupaten Rokan Hilir',
    'label': 'Riau, Kabupaten Rokan Hilir',
  },
  {
    'province': 'Riau',
    'city': 'Kabupaten Kepulauan Meranti',
    'label': 'Riau, Kabupaten Kepulauan Meranti',
  },
  {
    'province': 'Riau',
    'city': 'Kota Pekanbaru',
    'label': 'Riau, Kota Pekanbaru',
  },
  {
    'province': 'Riau',
    'city': 'Kota D U M A I',
    'label': 'Riau, Kota D U M A I',
  },
  {
    'province': 'Jambi',
    'city': 'Kabupaten Kerinci',
    'label': 'Jambi, Kabupaten Kerinci',
  },
  {
    'province': 'Jambi',
    'city': 'Kabupaten Merangin',
    'label': 'Jambi, Kabupaten Merangin',
  },
  {
    'province': 'Jambi',
    'city': 'Kabupaten Sarolangun',
    'label': 'Jambi, Kabupaten Sarolangun',
  },
  {
    'province': 'Jambi',
    'city': 'Kabupaten Batang Hari',
    'label': 'Jambi, Kabupaten Batang Hari',
  },
  {
    'province': 'Jambi',
    'city': 'Kabupaten Muaro Jambi',
    'label': 'Jambi, Kabupaten Muaro Jambi',
  },
  {
    'province': 'Jambi',
    'city': 'Kabupaten Tanjung Jabung Timur',
    'label': 'Jambi, Kabupaten Tanjung Jabung Timur',
  },
  {
    'province': 'Jambi',
    'city': 'Kabupaten Tanjung Jabung Barat',
    'label': 'Jambi, Kabupaten Tanjung Jabung Barat',
  },
  {
    'province': 'Jambi',
    'city': 'Kabupaten Tebo',
    'label': 'Jambi, Kabupaten Tebo',
  },
  {
    'province': 'Jambi',
    'city': 'Kabupaten Bungo',
    'label': 'Jambi, Kabupaten Bungo',
  },
  {'province': 'Jambi', 'city': 'Kota Jambi', 'label': 'Jambi, Kota Jambi'},
  {
    'province': 'Jambi',
    'city': 'Kota Sungai Penuh',
    'label': 'Jambi, Kota Sungai Penuh',
  },
  {
    'province': 'Sumatera Selatan',
    'city': 'Kabupaten Ogan Komering Ulu',
    'label': 'Sumatera Selatan, Kabupaten Ogan Komering Ulu',
  },
  {
    'province': 'Sumatera Selatan',
    'city': 'Kabupaten Ogan Komering Ilir',
    'label': 'Sumatera Selatan, Kabupaten Ogan Komering Ilir',
  },
  {
    'province': 'Sumatera Selatan',
    'city': 'Kabupaten Muara Enim',
    'label': 'Sumatera Selatan, Kabupaten Muara Enim',
  },
  {
    'province': 'Sumatera Selatan',
    'city': 'Kabupaten Lahat',
    'label': 'Sumatera Selatan, Kabupaten Lahat',
  },
  {
    'province': 'Sumatera Selatan',
    'city': 'Kabupaten Musi Rawas',
    'label': 'Sumatera Selatan, Kabupaten Musi Rawas',
  },
  {
    'province': 'Sumatera Selatan',
    'city': 'Kabupaten Musi Banyuasin',
    'label': 'Sumatera Selatan, Kabupaten Musi Banyuasin',
  },
  {
    'province': 'Sumatera Selatan',
    'city': 'Kabupaten Banyu Asin',
    'label': 'Sumatera Selatan, Kabupaten Banyu Asin',
  },
  {
    'province': 'Sumatera Selatan',
    'city': 'Kabupaten Ogan Komering Ulu Selatan',
    'label': 'Sumatera Selatan, Kabupaten Ogan Komering Ulu Selatan',
  },
  {
    'province': 'Sumatera Selatan',
    'city': 'Kabupaten Ogan Komering Ulu Timur',
    'label': 'Sumatera Selatan, Kabupaten Ogan Komering Ulu Timur',
  },
  {
    'province': 'Sumatera Selatan',
    'city': 'Kabupaten Ogan Ilir',
    'label': 'Sumatera Selatan, Kabupaten Ogan Ilir',
  },
  {
    'province': 'Sumatera Selatan',
    'city': 'Kabupaten Empat Lawang',
    'label': 'Sumatera Selatan, Kabupaten Empat Lawang',
  },
  {
    'province': 'Sumatera Selatan',
    'city': 'Kabupaten Penukal Abab Lematang Ilir',
    'label': 'Sumatera Selatan, Kabupaten Penukal Abab Lematang Ilir',
  },
  {
    'province': 'Sumatera Selatan',
    'city': 'Kabupaten Musi Rawas Utara',
    'label': 'Sumatera Selatan, Kabupaten Musi Rawas Utara',
  },
  {
    'province': 'Sumatera Selatan',
    'city': 'Kota Palembang',
    'label': 'Sumatera Selatan, Kota Palembang',
  },
  {
    'province': 'Sumatera Selatan',
    'city': 'Kota Prabumulih',
    'label': 'Sumatera Selatan, Kota Prabumulih',
  },
  {
    'province': 'Sumatera Selatan',
    'city': 'Kota Pagar Alam',
    'label': 'Sumatera Selatan, Kota Pagar Alam',
  },
  {
    'province': 'Sumatera Selatan',
    'city': 'Kota Lubuklinggau',
    'label': 'Sumatera Selatan, Kota Lubuklinggau',
  },
  {
    'province': 'Bengkulu',
    'city': 'Kabupaten Bengkulu Selatan',
    'label': 'Bengkulu, Kabupaten Bengkulu Selatan',
  },
  {
    'province': 'Bengkulu',
    'city': 'Kabupaten Rejang Lebong',
    'label': 'Bengkulu, Kabupaten Rejang Lebong',
  },
  {
    'province': 'Bengkulu',
    'city': 'Kabupaten Bengkulu Utara',
    'label': 'Bengkulu, Kabupaten Bengkulu Utara',
  },
  {
    'province': 'Bengkulu',
    'city': 'Kabupaten Kaur',
    'label': 'Bengkulu, Kabupaten Kaur',
  },
  {
    'province': 'Bengkulu',
    'city': 'Kabupaten Seluma',
    'label': 'Bengkulu, Kabupaten Seluma',
  },
  {
    'province': 'Bengkulu',
    'city': 'Kabupaten Mukomuko',
    'label': 'Bengkulu, Kabupaten Mukomuko',
  },
  {
    'province': 'Bengkulu',
    'city': 'Kabupaten Lebong',
    'label': 'Bengkulu, Kabupaten Lebong',
  },
  {
    'province': 'Bengkulu',
    'city': 'Kabupaten Kepahiang',
    'label': 'Bengkulu, Kabupaten Kepahiang',
  },
  {
    'province': 'Bengkulu',
    'city': 'Kabupaten Bengkulu Tengah',
    'label': 'Bengkulu, Kabupaten Bengkulu Tengah',
  },
  {
    'province': 'Bengkulu',
    'city': 'Kota Bengkulu',
    'label': 'Bengkulu, Kota Bengkulu',
  },
  {
    'province': 'Lampung',
    'city': 'Kabupaten Lampung Barat',
    'label': 'Lampung, Kabupaten Lampung Barat',
  },
  {
    'province': 'Lampung',
    'city': 'Kabupaten Tanggamus',
    'label': 'Lampung, Kabupaten Tanggamus',
  },
  {
    'province': 'Lampung',
    'city': 'Kabupaten Lampung Selatan',
    'label': 'Lampung, Kabupaten Lampung Selatan',
  },
  {
    'province': 'Lampung',
    'city': 'Kabupaten Lampung Timur',
    'label': 'Lampung, Kabupaten Lampung Timur',
  },
  {
    'province': 'Lampung',
    'city': 'Kabupaten Lampung Tengah',
    'label': 'Lampung, Kabupaten Lampung Tengah',
  },
  {
    'province': 'Lampung',
    'city': 'Kabupaten Lampung Utara',
    'label': 'Lampung, Kabupaten Lampung Utara',
  },
  {
    'province': 'Lampung',
    'city': 'Kabupaten Way Kanan',
    'label': 'Lampung, Kabupaten Way Kanan',
  },
  {
    'province': 'Lampung',
    'city': 'Kabupaten Tulangbawang',
    'label': 'Lampung, Kabupaten Tulangbawang',
  },
  {
    'province': 'Lampung',
    'city': 'Kabupaten Pesawaran',
    'label': 'Lampung, Kabupaten Pesawaran',
  },
  {
    'province': 'Lampung',
    'city': 'Kabupaten Pringsewu',
    'label': 'Lampung, Kabupaten Pringsewu',
  },
  {
    'province': 'Lampung',
    'city': 'Kabupaten Mesuji',
    'label': 'Lampung, Kabupaten Mesuji',
  },
  {
    'province': 'Lampung',
    'city': 'Kabupaten Tulang Bawang Barat',
    'label': 'Lampung, Kabupaten Tulang Bawang Barat',
  },
  {
    'province': 'Lampung',
    'city': 'Kabupaten Pesisir Barat',
    'label': 'Lampung, Kabupaten Pesisir Barat',
  },
  {
    'province': 'Lampung',
    'city': 'Kota Bandar Lampung',
    'label': 'Lampung, Kota Bandar Lampung',
  },
  {'province': 'Lampung', 'city': 'Kota Metro', 'label': 'Lampung, Kota Metro'},
  {
    'province': 'Kepulauan Bangka Belitung',
    'city': 'Kabupaten Bangka',
    'label': 'Kepulauan Bangka Belitung, Kabupaten Bangka',
  },
  {
    'province': 'Kepulauan Bangka Belitung',
    'city': 'Kabupaten Belitung',
    'label': 'Kepulauan Bangka Belitung, Kabupaten Belitung',
  },
  {
    'province': 'Kepulauan Bangka Belitung',
    'city': 'Kabupaten Bangka Barat',
    'label': 'Kepulauan Bangka Belitung, Kabupaten Bangka Barat',
  },
  {
    'province': 'Kepulauan Bangka Belitung',
    'city': 'Kabupaten Bangka Tengah',
    'label': 'Kepulauan Bangka Belitung, Kabupaten Bangka Tengah',
  },
  {
    'province': 'Kepulauan Bangka Belitung',
    'city': 'Kabupaten Bangka Selatan',
    'label': 'Kepulauan Bangka Belitung, Kabupaten Bangka Selatan',
  },
  {
    'province': 'Kepulauan Bangka Belitung',
    'city': 'Kabupaten Belitung Timur',
    'label': 'Kepulauan Bangka Belitung, Kabupaten Belitung Timur',
  },
  {
    'province': 'Kepulauan Bangka Belitung',
    'city': 'Kota Pangkal Pinang',
    'label': 'Kepulauan Bangka Belitung, Kota Pangkal Pinang',
  },
  {
    'province': 'Kepulauan Riau',
    'city': 'Kabupaten Karimun',
    'label': 'Kepulauan Riau, Kabupaten Karimun',
  },
  {
    'province': 'Kepulauan Riau',
    'city': 'Kabupaten Bintan',
    'label': 'Kepulauan Riau, Kabupaten Bintan',
  },
  {
    'province': 'Kepulauan Riau',
    'city': 'Kabupaten Natuna',
    'label': 'Kepulauan Riau, Kabupaten Natuna',
  },
  {
    'province': 'Kepulauan Riau',
    'city': 'Kabupaten Lingga',
    'label': 'Kepulauan Riau, Kabupaten Lingga',
  },
  {
    'province': 'Kepulauan Riau',
    'city': 'Kabupaten Kepulauan Anambas',
    'label': 'Kepulauan Riau, Kabupaten Kepulauan Anambas',
  },
  {
    'province': 'Kepulauan Riau',
    'city': 'Kota B A T A M',
    'label': 'Kepulauan Riau, Kota B A T A M',
  },
  {
    'province': 'Kepulauan Riau',
    'city': 'Kota Tanjung Pinang',
    'label': 'Kepulauan Riau, Kota Tanjung Pinang',
  },
  {
    'province': 'Dki Jakarta',
    'city': 'Kabupaten Kepulauan Seribu',
    'label': 'Dki Jakarta, Kabupaten Kepulauan Seribu',
  },
  {
    'province': 'Dki Jakarta',
    'city': 'Kota Jakarta Selatan',
    'label': 'Dki Jakarta, Kota Jakarta Selatan',
  },
  {
    'province': 'Dki Jakarta',
    'city': 'Kota Jakarta Timur',
    'label': 'Dki Jakarta, Kota Jakarta Timur',
  },
  {
    'province': 'Dki Jakarta',
    'city': 'Kota Jakarta Pusat',
    'label': 'Dki Jakarta, Kota Jakarta Pusat',
  },
  {
    'province': 'Dki Jakarta',
    'city': 'Kota Jakarta Barat',
    'label': 'Dki Jakarta, Kota Jakarta Barat',
  },
  {
    'province': 'Dki Jakarta',
    'city': 'Kota Jakarta Utara',
    'label': 'Dki Jakarta, Kota Jakarta Utara',
  },
  {
    'province': 'Jawa Barat',
    'city': 'Kabupaten Bogor',
    'label': 'Jawa Barat, Kabupaten Bogor',
  },
  {
    'province': 'Jawa Barat',
    'city': 'Kabupaten Sukabumi',
    'label': 'Jawa Barat, Kabupaten Sukabumi',
  },
  {
    'province': 'Jawa Barat',
    'city': 'Kabupaten Cianjur',
    'label': 'Jawa Barat, Kabupaten Cianjur',
  },
  {
    'province': 'Jawa Barat',
    'city': 'Kabupaten Bandung',
    'label': 'Jawa Barat, Kabupaten Bandung',
  },
  {
    'province': 'Jawa Barat',
    'city': 'Kabupaten Garut',
    'label': 'Jawa Barat, Kabupaten Garut',
  },
  {
    'province': 'Jawa Barat',
    'city': 'Kabupaten Tasikmalaya',
    'label': 'Jawa Barat, Kabupaten Tasikmalaya',
  },
  {
    'province': 'Jawa Barat',
    'city': 'Kabupaten Ciamis',
    'label': 'Jawa Barat, Kabupaten Ciamis',
  },
  {
    'province': 'Jawa Barat',
    'city': 'Kabupaten Kuningan',
    'label': 'Jawa Barat, Kabupaten Kuningan',
  },
  {
    'province': 'Jawa Barat',
    'city': 'Kabupaten Cirebon',
    'label': 'Jawa Barat, Kabupaten Cirebon',
  },
  {
    'province': 'Jawa Barat',
    'city': 'Kabupaten Majalengka',
    'label': 'Jawa Barat, Kabupaten Majalengka',
  },
  {
    'province': 'Jawa Barat',
    'city': 'Kabupaten Sumedang',
    'label': 'Jawa Barat, Kabupaten Sumedang',
  },
  {
    'province': 'Jawa Barat',
    'city': 'Kabupaten Indramayu',
    'label': 'Jawa Barat, Kabupaten Indramayu',
  },
  {
    'province': 'Jawa Barat',
    'city': 'Kabupaten Subang',
    'label': 'Jawa Barat, Kabupaten Subang',
  },
  {
    'province': 'Jawa Barat',
    'city': 'Kabupaten Purwakarta',
    'label': 'Jawa Barat, Kabupaten Purwakarta',
  },
  {
    'province': 'Jawa Barat',
    'city': 'Kabupaten Karawang',
    'label': 'Jawa Barat, Kabupaten Karawang',
  },
  {
    'province': 'Jawa Barat',
    'city': 'Kabupaten Bekasi',
    'label': 'Jawa Barat, Kabupaten Bekasi',
  },
  {
    'province': 'Jawa Barat',
    'city': 'Kabupaten Bandung Barat',
    'label': 'Jawa Barat, Kabupaten Bandung Barat',
  },
  {
    'province': 'Jawa Barat',
    'city': 'Kabupaten Pangandaran',
    'label': 'Jawa Barat, Kabupaten Pangandaran',
  },
  {
    'province': 'Jawa Barat',
    'city': 'Kota Bogor',
    'label': 'Jawa Barat, Kota Bogor',
  },
  {
    'province': 'Jawa Barat',
    'city': 'Kota Sukabumi',
    'label': 'Jawa Barat, Kota Sukabumi',
  },
  {
    'province': 'Jawa Barat',
    'city': 'Kota Bandung',
    'label': 'Jawa Barat, Kota Bandung',
  },
  {
    'province': 'Jawa Barat',
    'city': 'Kota Cirebon',
    'label': 'Jawa Barat, Kota Cirebon',
  },
  {
    'province': 'Jawa Barat',
    'city': 'Kota Bekasi',
    'label': 'Jawa Barat, Kota Bekasi',
  },
  {
    'province': 'Jawa Barat',
    'city': 'Kota Depok',
    'label': 'Jawa Barat, Kota Depok',
  },
  {
    'province': 'Jawa Barat',
    'city': 'Kota Cimahi',
    'label': 'Jawa Barat, Kota Cimahi',
  },
  {
    'province': 'Jawa Barat',
    'city': 'Kota Tasikmalaya',
    'label': 'Jawa Barat, Kota Tasikmalaya',
  },
  {
    'province': 'Jawa Barat',
    'city': 'Kota Banjar',
    'label': 'Jawa Barat, Kota Banjar',
  },
  {
    'province': 'Jawa Tengah',
    'city': 'Kabupaten Cilacap',
    'label': 'Jawa Tengah, Kabupaten Cilacap',
  },
  {
    'province': 'Jawa Tengah',
    'city': 'Kabupaten Banyumas',
    'label': 'Jawa Tengah, Kabupaten Banyumas',
  },
  {
    'province': 'Jawa Tengah',
    'city': 'Kabupaten Purbalingga',
    'label': 'Jawa Tengah, Kabupaten Purbalingga',
  },
  {
    'province': 'Jawa Tengah',
    'city': 'Kabupaten Banjarnegara',
    'label': 'Jawa Tengah, Kabupaten Banjarnegara',
  },
  {
    'province': 'Jawa Tengah',
    'city': 'Kabupaten Kebumen',
    'label': 'Jawa Tengah, Kabupaten Kebumen',
  },
  {
    'province': 'Jawa Tengah',
    'city': 'Kabupaten Purworejo',
    'label': 'Jawa Tengah, Kabupaten Purworejo',
  },
  {
    'province': 'Jawa Tengah',
    'city': 'Kabupaten Wonosobo',
    'label': 'Jawa Tengah, Kabupaten Wonosobo',
  },
  {
    'province': 'Jawa Tengah',
    'city': 'Kabupaten Magelang',
    'label': 'Jawa Tengah, Kabupaten Magelang',
  },
  {
    'province': 'Jawa Tengah',
    'city': 'Kabupaten Boyolali',
    'label': 'Jawa Tengah, Kabupaten Boyolali',
  },
  {
    'province': 'Jawa Tengah',
    'city': 'Kabupaten Klaten',
    'label': 'Jawa Tengah, Kabupaten Klaten',
  },
  {
    'province': 'Jawa Tengah',
    'city': 'Kabupaten Sukoharjo',
    'label': 'Jawa Tengah, Kabupaten Sukoharjo',
  },
  {
    'province': 'Jawa Tengah',
    'city': 'Kabupaten Wonogiri',
    'label': 'Jawa Tengah, Kabupaten Wonogiri',
  },
  {
    'province': 'Jawa Tengah',
    'city': 'Kabupaten Karanganyar',
    'label': 'Jawa Tengah, Kabupaten Karanganyar',
  },
  {
    'province': 'Jawa Tengah',
    'city': 'Kabupaten Sragen',
    'label': 'Jawa Tengah, Kabupaten Sragen',
  },
  {
    'province': 'Jawa Tengah',
    'city': 'Kabupaten Grobogan',
    'label': 'Jawa Tengah, Kabupaten Grobogan',
  },
  {
    'province': 'Jawa Tengah',
    'city': 'Kabupaten Blora',
    'label': 'Jawa Tengah, Kabupaten Blora',
  },
  {
    'province': 'Jawa Tengah',
    'city': 'Kabupaten Rembang',
    'label': 'Jawa Tengah, Kabupaten Rembang',
  },
  {
    'province': 'Jawa Tengah',
    'city': 'Kabupaten Pati',
    'label': 'Jawa Tengah, Kabupaten Pati',
  },
  {
    'province': 'Jawa Tengah',
    'city': 'Kabupaten Kudus',
    'label': 'Jawa Tengah, Kabupaten Kudus',
  },
  {
    'province': 'Jawa Tengah',
    'city': 'Kabupaten Jepara',
    'label': 'Jawa Tengah, Kabupaten Jepara',
  },
  {
    'province': 'Jawa Tengah',
    'city': 'Kabupaten Demak',
    'label': 'Jawa Tengah, Kabupaten Demak',
  },
  {
    'province': 'Jawa Tengah',
    'city': 'Kabupaten Semarang',
    'label': 'Jawa Tengah, Kabupaten Semarang',
  },
  {
    'province': 'Jawa Tengah',
    'city': 'Kabupaten Temanggung',
    'label': 'Jawa Tengah, Kabupaten Temanggung',
  },
  {
    'province': 'Jawa Tengah',
    'city': 'Kabupaten Kendal',
    'label': 'Jawa Tengah, Kabupaten Kendal',
  },
  {
    'province': 'Jawa Tengah',
    'city': 'Kabupaten Batang',
    'label': 'Jawa Tengah, Kabupaten Batang',
  },
  {
    'province': 'Jawa Tengah',
    'city': 'Kabupaten Pekalongan',
    'label': 'Jawa Tengah, Kabupaten Pekalongan',
  },
  {
    'province': 'Jawa Tengah',
    'city': 'Kabupaten Pemalang',
    'label': 'Jawa Tengah, Kabupaten Pemalang',
  },
  {
    'province': 'Jawa Tengah',
    'city': 'Kabupaten Tegal',
    'label': 'Jawa Tengah, Kabupaten Tegal',
  },
  {
    'province': 'Jawa Tengah',
    'city': 'Kabupaten Brebes',
    'label': 'Jawa Tengah, Kabupaten Brebes',
  },
  {
    'province': 'Jawa Tengah',
    'city': 'Kota Magelang',
    'label': 'Jawa Tengah, Kota Magelang',
  },
  {
    'province': 'Jawa Tengah',
    'city': 'Kota Surakarta',
    'label': 'Jawa Tengah, Kota Surakarta',
  },
  {
    'province': 'Jawa Tengah',
    'city': 'Kota Salatiga',
    'label': 'Jawa Tengah, Kota Salatiga',
  },
  {
    'province': 'Jawa Tengah',
    'city': 'Kota Semarang',
    'label': 'Jawa Tengah, Kota Semarang',
  },
  {
    'province': 'Jawa Tengah',
    'city': 'Kota Pekalongan',
    'label': 'Jawa Tengah, Kota Pekalongan',
  },
  {
    'province': 'Jawa Tengah',
    'city': 'Kota Tegal',
    'label': 'Jawa Tengah, Kota Tegal',
  },
  {
    'province': 'Di Yogyakarta',
    'city': 'Kabupaten Kulon Progo',
    'label': 'Di Yogyakarta, Kabupaten Kulon Progo',
  },
  {
    'province': 'Di Yogyakarta',
    'city': 'Kabupaten Bantul',
    'label': 'Di Yogyakarta, Kabupaten Bantul',
  },
  {
    'province': 'Di Yogyakarta',
    'city': 'Kabupaten Gunung Kidul',
    'label': 'Di Yogyakarta, Kabupaten Gunung Kidul',
  },
  {
    'province': 'Di Yogyakarta',
    'city': 'Kabupaten Sleman',
    'label': 'Di Yogyakarta, Kabupaten Sleman',
  },
  {
    'province': 'Di Yogyakarta',
    'city': 'Kota Yogyakarta',
    'label': 'Di Yogyakarta, Kota Yogyakarta',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kabupaten Pacitan',
    'label': 'Jawa Timur, Kabupaten Pacitan',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kabupaten Ponorogo',
    'label': 'Jawa Timur, Kabupaten Ponorogo',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kabupaten Trenggalek',
    'label': 'Jawa Timur, Kabupaten Trenggalek',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kabupaten Tulungagung',
    'label': 'Jawa Timur, Kabupaten Tulungagung',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kabupaten Blitar',
    'label': 'Jawa Timur, Kabupaten Blitar',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kabupaten Kediri',
    'label': 'Jawa Timur, Kabupaten Kediri',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kabupaten Malang',
    'label': 'Jawa Timur, Kabupaten Malang',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kabupaten Lumajang',
    'label': 'Jawa Timur, Kabupaten Lumajang',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kabupaten Jember',
    'label': 'Jawa Timur, Kabupaten Jember',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kabupaten Banyuwangi',
    'label': 'Jawa Timur, Kabupaten Banyuwangi',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kabupaten Bondowoso',
    'label': 'Jawa Timur, Kabupaten Bondowoso',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kabupaten Situbondo',
    'label': 'Jawa Timur, Kabupaten Situbondo',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kabupaten Probolinggo',
    'label': 'Jawa Timur, Kabupaten Probolinggo',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kabupaten Pasuruan',
    'label': 'Jawa Timur, Kabupaten Pasuruan',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kabupaten Sidoarjo',
    'label': 'Jawa Timur, Kabupaten Sidoarjo',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kabupaten Mojokerto',
    'label': 'Jawa Timur, Kabupaten Mojokerto',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kabupaten Jombang',
    'label': 'Jawa Timur, Kabupaten Jombang',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kabupaten Nganjuk',
    'label': 'Jawa Timur, Kabupaten Nganjuk',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kabupaten Madiun',
    'label': 'Jawa Timur, Kabupaten Madiun',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kabupaten Magetan',
    'label': 'Jawa Timur, Kabupaten Magetan',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kabupaten Ngawi',
    'label': 'Jawa Timur, Kabupaten Ngawi',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kabupaten Bojonegoro',
    'label': 'Jawa Timur, Kabupaten Bojonegoro',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kabupaten Tuban',
    'label': 'Jawa Timur, Kabupaten Tuban',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kabupaten Lamongan',
    'label': 'Jawa Timur, Kabupaten Lamongan',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kabupaten Gresik',
    'label': 'Jawa Timur, Kabupaten Gresik',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kabupaten Bangkalan',
    'label': 'Jawa Timur, Kabupaten Bangkalan',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kabupaten Sampang',
    'label': 'Jawa Timur, Kabupaten Sampang',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kabupaten Pamekasan',
    'label': 'Jawa Timur, Kabupaten Pamekasan',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kabupaten Sumenep',
    'label': 'Jawa Timur, Kabupaten Sumenep',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kota Kediri',
    'label': 'Jawa Timur, Kota Kediri',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kota Blitar',
    'label': 'Jawa Timur, Kota Blitar',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kota Malang',
    'label': 'Jawa Timur, Kota Malang',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kota Probolinggo',
    'label': 'Jawa Timur, Kota Probolinggo',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kota Pasuruan',
    'label': 'Jawa Timur, Kota Pasuruan',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kota Mojokerto',
    'label': 'Jawa Timur, Kota Mojokerto',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kota Madiun',
    'label': 'Jawa Timur, Kota Madiun',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kota Surabaya',
    'label': 'Jawa Timur, Kota Surabaya',
  },
  {
    'province': 'Jawa Timur',
    'city': 'Kota Batu',
    'label': 'Jawa Timur, Kota Batu',
  },
  {
    'province': 'Banten',
    'city': 'Kabupaten Pandeglang',
    'label': 'Banten, Kabupaten Pandeglang',
  },
  {
    'province': 'Banten',
    'city': 'Kabupaten Lebak',
    'label': 'Banten, Kabupaten Lebak',
  },
  {
    'province': 'Banten',
    'city': 'Kabupaten Tangerang',
    'label': 'Banten, Kabupaten Tangerang',
  },
  {
    'province': 'Banten',
    'city': 'Kabupaten Serang',
    'label': 'Banten, Kabupaten Serang',
  },
  {
    'province': 'Banten',
    'city': 'Kota Tangerang',
    'label': 'Banten, Kota Tangerang',
  },
  {
    'province': 'Banten',
    'city': 'Kota Cilegon',
    'label': 'Banten, Kota Cilegon',
  },
  {'province': 'Banten', 'city': 'Kota Serang', 'label': 'Banten, Kota Serang'},
  {
    'province': 'Banten',
    'city': 'Kota Tangerang Selatan',
    'label': 'Banten, Kota Tangerang Selatan',
  },
  {
    'province': 'Bali',
    'city': 'Kabupaten Jembrana',
    'label': 'Bali, Kabupaten Jembrana',
  },
  {
    'province': 'Bali',
    'city': 'Kabupaten Tabanan',
    'label': 'Bali, Kabupaten Tabanan',
  },
  {
    'province': 'Bali',
    'city': 'Kabupaten Badung',
    'label': 'Bali, Kabupaten Badung',
  },
  {
    'province': 'Bali',
    'city': 'Kabupaten Gianyar',
    'label': 'Bali, Kabupaten Gianyar',
  },
  {
    'province': 'Bali',
    'city': 'Kabupaten Klungkung',
    'label': 'Bali, Kabupaten Klungkung',
  },
  {
    'province': 'Bali',
    'city': 'Kabupaten Bangli',
    'label': 'Bali, Kabupaten Bangli',
  },
  {
    'province': 'Bali',
    'city': 'Kabupaten Karang Asem',
    'label': 'Bali, Kabupaten Karang Asem',
  },
  {
    'province': 'Bali',
    'city': 'Kabupaten Buleleng',
    'label': 'Bali, Kabupaten Buleleng',
  },
  {'province': 'Bali', 'city': 'Kota Denpasar', 'label': 'Bali, Kota Denpasar'},
  {
    'province': 'Nusa Tenggara Barat',
    'city': 'Kabupaten Lombok Barat',
    'label': 'Nusa Tenggara Barat, Kabupaten Lombok Barat',
  },
  {
    'province': 'Nusa Tenggara Barat',
    'city': 'Kabupaten Lombok Tengah',
    'label': 'Nusa Tenggara Barat, Kabupaten Lombok Tengah',
  },
  {
    'province': 'Nusa Tenggara Barat',
    'city': 'Kabupaten Lombok Timur',
    'label': 'Nusa Tenggara Barat, Kabupaten Lombok Timur',
  },
  {
    'province': 'Nusa Tenggara Barat',
    'city': 'Kabupaten Sumbawa',
    'label': 'Nusa Tenggara Barat, Kabupaten Sumbawa',
  },
  {
    'province': 'Nusa Tenggara Barat',
    'city': 'Kabupaten Dompu',
    'label': 'Nusa Tenggara Barat, Kabupaten Dompu',
  },
  {
    'province': 'Nusa Tenggara Barat',
    'city': 'Kabupaten Bima',
    'label': 'Nusa Tenggara Barat, Kabupaten Bima',
  },
  {
    'province': 'Nusa Tenggara Barat',
    'city': 'Kabupaten Sumbawa Barat',
    'label': 'Nusa Tenggara Barat, Kabupaten Sumbawa Barat',
  },
  {
    'province': 'Nusa Tenggara Barat',
    'city': 'Kabupaten Lombok Utara',
    'label': 'Nusa Tenggara Barat, Kabupaten Lombok Utara',
  },
  {
    'province': 'Nusa Tenggara Barat',
    'city': 'Kota Mataram',
    'label': 'Nusa Tenggara Barat, Kota Mataram',
  },
  {
    'province': 'Nusa Tenggara Barat',
    'city': 'Kota Bima',
    'label': 'Nusa Tenggara Barat, Kota Bima',
  },
  {
    'province': 'Nusa Tenggara Timur',
    'city': 'Kabupaten Sumba Barat',
    'label': 'Nusa Tenggara Timur, Kabupaten Sumba Barat',
  },
  {
    'province': 'Nusa Tenggara Timur',
    'city': 'Kabupaten Sumba Timur',
    'label': 'Nusa Tenggara Timur, Kabupaten Sumba Timur',
  },
  {
    'province': 'Nusa Tenggara Timur',
    'city': 'Kabupaten Kupang',
    'label': 'Nusa Tenggara Timur, Kabupaten Kupang',
  },
  {
    'province': 'Nusa Tenggara Timur',
    'city': 'Kabupaten Timor Tengah Selatan',
    'label': 'Nusa Tenggara Timur, Kabupaten Timor Tengah Selatan',
  },
  {
    'province': 'Nusa Tenggara Timur',
    'city': 'Kabupaten Timor Tengah Utara',
    'label': 'Nusa Tenggara Timur, Kabupaten Timor Tengah Utara',
  },
  {
    'province': 'Nusa Tenggara Timur',
    'city': 'Kabupaten Belu',
    'label': 'Nusa Tenggara Timur, Kabupaten Belu',
  },
  {
    'province': 'Nusa Tenggara Timur',
    'city': 'Kabupaten Alor',
    'label': 'Nusa Tenggara Timur, Kabupaten Alor',
  },
  {
    'province': 'Nusa Tenggara Timur',
    'city': 'Kabupaten Lembata',
    'label': 'Nusa Tenggara Timur, Kabupaten Lembata',
  },
  {
    'province': 'Nusa Tenggara Timur',
    'city': 'Kabupaten Flores Timur',
    'label': 'Nusa Tenggara Timur, Kabupaten Flores Timur',
  },
  {
    'province': 'Nusa Tenggara Timur',
    'city': 'Kabupaten Sikka',
    'label': 'Nusa Tenggara Timur, Kabupaten Sikka',
  },
  {
    'province': 'Nusa Tenggara Timur',
    'city': 'Kabupaten Ende',
    'label': 'Nusa Tenggara Timur, Kabupaten Ende',
  },
  {
    'province': 'Nusa Tenggara Timur',
    'city': 'Kabupaten Ngada',
    'label': 'Nusa Tenggara Timur, Kabupaten Ngada',
  },
  {
    'province': 'Nusa Tenggara Timur',
    'city': 'Kabupaten Manggarai',
    'label': 'Nusa Tenggara Timur, Kabupaten Manggarai',
  },
  {
    'province': 'Nusa Tenggara Timur',
    'city': 'Kabupaten Rote Ndao',
    'label': 'Nusa Tenggara Timur, Kabupaten Rote Ndao',
  },
  {
    'province': 'Nusa Tenggara Timur',
    'city': 'Kabupaten Manggarai Barat',
    'label': 'Nusa Tenggara Timur, Kabupaten Manggarai Barat',
  },
  {
    'province': 'Nusa Tenggara Timur',
    'city': 'Kabupaten Sumba Tengah',
    'label': 'Nusa Tenggara Timur, Kabupaten Sumba Tengah',
  },
  {
    'province': 'Nusa Tenggara Timur',
    'city': 'Kabupaten Sumba Barat Daya',
    'label': 'Nusa Tenggara Timur, Kabupaten Sumba Barat Daya',
  },
  {
    'province': 'Nusa Tenggara Timur',
    'city': 'Kabupaten Nagekeo',
    'label': 'Nusa Tenggara Timur, Kabupaten Nagekeo',
  },
  {
    'province': 'Nusa Tenggara Timur',
    'city': 'Kabupaten Manggarai Timur',
    'label': 'Nusa Tenggara Timur, Kabupaten Manggarai Timur',
  },
  {
    'province': 'Nusa Tenggara Timur',
    'city': 'Kabupaten Sabu Raijua',
    'label': 'Nusa Tenggara Timur, Kabupaten Sabu Raijua',
  },
  {
    'province': 'Nusa Tenggara Timur',
    'city': 'Kabupaten Malaka',
    'label': 'Nusa Tenggara Timur, Kabupaten Malaka',
  },
  {
    'province': 'Nusa Tenggara Timur',
    'city': 'Kota Kupang',
    'label': 'Nusa Tenggara Timur, Kota Kupang',
  },
  {
    'province': 'Kalimantan Barat',
    'city': 'Kabupaten Sambas',
    'label': 'Kalimantan Barat, Kabupaten Sambas',
  },
  {
    'province': 'Kalimantan Barat',
    'city': 'Kabupaten Bengkayang',
    'label': 'Kalimantan Barat, Kabupaten Bengkayang',
  },
  {
    'province': 'Kalimantan Barat',
    'city': 'Kabupaten Landak',
    'label': 'Kalimantan Barat, Kabupaten Landak',
  },
  {
    'province': 'Kalimantan Barat',
    'city': 'Kabupaten Mempawah',
    'label': 'Kalimantan Barat, Kabupaten Mempawah',
  },
  {
    'province': 'Kalimantan Barat',
    'city': 'Kabupaten Sanggau',
    'label': 'Kalimantan Barat, Kabupaten Sanggau',
  },
  {
    'province': 'Kalimantan Barat',
    'city': 'Kabupaten Ketapang',
    'label': 'Kalimantan Barat, Kabupaten Ketapang',
  },
  {
    'province': 'Kalimantan Barat',
    'city': 'Kabupaten Sintang',
    'label': 'Kalimantan Barat, Kabupaten Sintang',
  },
  {
    'province': 'Kalimantan Barat',
    'city': 'Kabupaten Kapuas Hulu',
    'label': 'Kalimantan Barat, Kabupaten Kapuas Hulu',
  },
  {
    'province': 'Kalimantan Barat',
    'city': 'Kabupaten Sekadau',
    'label': 'Kalimantan Barat, Kabupaten Sekadau',
  },
  {
    'province': 'Kalimantan Barat',
    'city': 'Kabupaten Melawi',
    'label': 'Kalimantan Barat, Kabupaten Melawi',
  },
  {
    'province': 'Kalimantan Barat',
    'city': 'Kabupaten Kayong Utara',
    'label': 'Kalimantan Barat, Kabupaten Kayong Utara',
  },
  {
    'province': 'Kalimantan Barat',
    'city': 'Kabupaten Kubu Raya',
    'label': 'Kalimantan Barat, Kabupaten Kubu Raya',
  },
  {
    'province': 'Kalimantan Barat',
    'city': 'Kota Pontianak',
    'label': 'Kalimantan Barat, Kota Pontianak',
  },
  {
    'province': 'Kalimantan Barat',
    'city': 'Kota Singkawang',
    'label': 'Kalimantan Barat, Kota Singkawang',
  },
  {
    'province': 'Kalimantan Tengah',
    'city': 'Kabupaten Kotawaringin Barat',
    'label': 'Kalimantan Tengah, Kabupaten Kotawaringin Barat',
  },
  {
    'province': 'Kalimantan Tengah',
    'city': 'Kabupaten Kotawaringin Timur',
    'label': 'Kalimantan Tengah, Kabupaten Kotawaringin Timur',
  },
  {
    'province': 'Kalimantan Tengah',
    'city': 'Kabupaten Kapuas',
    'label': 'Kalimantan Tengah, Kabupaten Kapuas',
  },
  {
    'province': 'Kalimantan Tengah',
    'city': 'Kabupaten Barito Selatan',
    'label': 'Kalimantan Tengah, Kabupaten Barito Selatan',
  },
  {
    'province': 'Kalimantan Tengah',
    'city': 'Kabupaten Barito Utara',
    'label': 'Kalimantan Tengah, Kabupaten Barito Utara',
  },
  {
    'province': 'Kalimantan Tengah',
    'city': 'Kabupaten Sukamara',
    'label': 'Kalimantan Tengah, Kabupaten Sukamara',
  },
  {
    'province': 'Kalimantan Tengah',
    'city': 'Kabupaten Lamandau',
    'label': 'Kalimantan Tengah, Kabupaten Lamandau',
  },
  {
    'province': 'Kalimantan Tengah',
    'city': 'Kabupaten Seruyan',
    'label': 'Kalimantan Tengah, Kabupaten Seruyan',
  },
  {
    'province': 'Kalimantan Tengah',
    'city': 'Kabupaten Katingan',
    'label': 'Kalimantan Tengah, Kabupaten Katingan',
  },
  {
    'province': 'Kalimantan Tengah',
    'city': 'Kabupaten Pulang Pisau',
    'label': 'Kalimantan Tengah, Kabupaten Pulang Pisau',
  },
  {
    'province': 'Kalimantan Tengah',
    'city': 'Kabupaten Gunung Mas',
    'label': 'Kalimantan Tengah, Kabupaten Gunung Mas',
  },
  {
    'province': 'Kalimantan Tengah',
    'city': 'Kabupaten Barito Timur',
    'label': 'Kalimantan Tengah, Kabupaten Barito Timur',
  },
  {
    'province': 'Kalimantan Tengah',
    'city': 'Kabupaten Murung Raya',
    'label': 'Kalimantan Tengah, Kabupaten Murung Raya',
  },
  {
    'province': 'Kalimantan Tengah',
    'city': 'Kota Palangka Raya',
    'label': 'Kalimantan Tengah, Kota Palangka Raya',
  },
  {
    'province': 'Kalimantan Selatan',
    'city': 'Kabupaten Tanah Laut',
    'label': 'Kalimantan Selatan, Kabupaten Tanah Laut',
  },
  {
    'province': 'Kalimantan Selatan',
    'city': 'Kabupaten Kota Baru',
    'label': 'Kalimantan Selatan, Kabupaten Kota Baru',
  },
  {
    'province': 'Kalimantan Selatan',
    'city': 'Kabupaten Banjar',
    'label': 'Kalimantan Selatan, Kabupaten Banjar',
  },
  {
    'province': 'Kalimantan Selatan',
    'city': 'Kabupaten Barito Kuala',
    'label': 'Kalimantan Selatan, Kabupaten Barito Kuala',
  },
  {
    'province': 'Kalimantan Selatan',
    'city': 'Kabupaten Tapin',
    'label': 'Kalimantan Selatan, Kabupaten Tapin',
  },
  {
    'province': 'Kalimantan Selatan',
    'city': 'Kabupaten Hulu Sungai Selatan',
    'label': 'Kalimantan Selatan, Kabupaten Hulu Sungai Selatan',
  },
  {
    'province': 'Kalimantan Selatan',
    'city': 'Kabupaten Hulu Sungai Tengah',
    'label': 'Kalimantan Selatan, Kabupaten Hulu Sungai Tengah',
  },
  {
    'province': 'Kalimantan Selatan',
    'city': 'Kabupaten Hulu Sungai Utara',
    'label': 'Kalimantan Selatan, Kabupaten Hulu Sungai Utara',
  },
  {
    'province': 'Kalimantan Selatan',
    'city': 'Kabupaten Tabalong',
    'label': 'Kalimantan Selatan, Kabupaten Tabalong',
  },
  {
    'province': 'Kalimantan Selatan',
    'city': 'Kabupaten Tanah Bumbu',
    'label': 'Kalimantan Selatan, Kabupaten Tanah Bumbu',
  },
  {
    'province': 'Kalimantan Selatan',
    'city': 'Kabupaten Balangan',
    'label': 'Kalimantan Selatan, Kabupaten Balangan',
  },
  {
    'province': 'Kalimantan Selatan',
    'city': 'Kota Banjarmasin',
    'label': 'Kalimantan Selatan, Kota Banjarmasin',
  },
  {
    'province': 'Kalimantan Selatan',
    'city': 'Kota Banjar Baru',
    'label': 'Kalimantan Selatan, Kota Banjar Baru',
  },
  {
    'province': 'Kalimantan Timur',
    'city': 'Kabupaten Paser',
    'label': 'Kalimantan Timur, Kabupaten Paser',
  },
  {
    'province': 'Kalimantan Timur',
    'city': 'Kabupaten Kutai Barat',
    'label': 'Kalimantan Timur, Kabupaten Kutai Barat',
  },
  {
    'province': 'Kalimantan Timur',
    'city': 'Kabupaten Kutai Kartanegara',
    'label': 'Kalimantan Timur, Kabupaten Kutai Kartanegara',
  },
  {
    'province': 'Kalimantan Timur',
    'city': 'Kabupaten Kutai Timur',
    'label': 'Kalimantan Timur, Kabupaten Kutai Timur',
  },
  {
    'province': 'Kalimantan Timur',
    'city': 'Kabupaten Berau',
    'label': 'Kalimantan Timur, Kabupaten Berau',
  },
  {
    'province': 'Kalimantan Timur',
    'city': 'Kabupaten Penajam Paser Utara',
    'label': 'Kalimantan Timur, Kabupaten Penajam Paser Utara',
  },
  {
    'province': 'Kalimantan Timur',
    'city': 'Kabupaten Mahakam Hulu',
    'label': 'Kalimantan Timur, Kabupaten Mahakam Hulu',
  },
  {
    'province': 'Kalimantan Timur',
    'city': 'Kota Balikpapan',
    'label': 'Kalimantan Timur, Kota Balikpapan',
  },
  {
    'province': 'Kalimantan Timur',
    'city': 'Kota Samarinda',
    'label': 'Kalimantan Timur, Kota Samarinda',
  },
  {
    'province': 'Kalimantan Timur',
    'city': 'Kota Bontang',
    'label': 'Kalimantan Timur, Kota Bontang',
  },
  {
    'province': 'Kalimantan Utara',
    'city': 'Kabupaten Malinau',
    'label': 'Kalimantan Utara, Kabupaten Malinau',
  },
  {
    'province': 'Kalimantan Utara',
    'city': 'Kabupaten Bulungan',
    'label': 'Kalimantan Utara, Kabupaten Bulungan',
  },
  {
    'province': 'Kalimantan Utara',
    'city': 'Kabupaten Tana Tidung',
    'label': 'Kalimantan Utara, Kabupaten Tana Tidung',
  },
  {
    'province': 'Kalimantan Utara',
    'city': 'Kabupaten Nunukan',
    'label': 'Kalimantan Utara, Kabupaten Nunukan',
  },
  {
    'province': 'Kalimantan Utara',
    'city': 'Kota Tarakan',
    'label': 'Kalimantan Utara, Kota Tarakan',
  },
  {
    'province': 'Sulawesi Utara',
    'city': 'Kabupaten Bolaang Mongondow',
    'label': 'Sulawesi Utara, Kabupaten Bolaang Mongondow',
  },
  {
    'province': 'Sulawesi Utara',
    'city': 'Kabupaten Minahasa',
    'label': 'Sulawesi Utara, Kabupaten Minahasa',
  },
  {
    'province': 'Sulawesi Utara',
    'city': 'Kabupaten Kepulauan Sangihe',
    'label': 'Sulawesi Utara, Kabupaten Kepulauan Sangihe',
  },
  {
    'province': 'Sulawesi Utara',
    'city': 'Kabupaten Kepulauan Talaud',
    'label': 'Sulawesi Utara, Kabupaten Kepulauan Talaud',
  },
  {
    'province': 'Sulawesi Utara',
    'city': 'Kabupaten Minahasa Selatan',
    'label': 'Sulawesi Utara, Kabupaten Minahasa Selatan',
  },
  {
    'province': 'Sulawesi Utara',
    'city': 'Kabupaten Minahasa Utara',
    'label': 'Sulawesi Utara, Kabupaten Minahasa Utara',
  },
  {
    'province': 'Sulawesi Utara',
    'city': 'Kabupaten Bolaang Mongondow Utara',
    'label': 'Sulawesi Utara, Kabupaten Bolaang Mongondow Utara',
  },
  {
    'province': 'Sulawesi Utara',
    'city': 'Kabupaten Siau Tagulandang Biaro',
    'label': 'Sulawesi Utara, Kabupaten Siau Tagulandang Biaro',
  },
  {
    'province': 'Sulawesi Utara',
    'city': 'Kabupaten Minahasa Tenggara',
    'label': 'Sulawesi Utara, Kabupaten Minahasa Tenggara',
  },
  {
    'province': 'Sulawesi Utara',
    'city': 'Kabupaten Bolaang Mongondow Selatan',
    'label': 'Sulawesi Utara, Kabupaten Bolaang Mongondow Selatan',
  },
  {
    'province': 'Sulawesi Utara',
    'city': 'Kabupaten Bolaang Mongondow Timur',
    'label': 'Sulawesi Utara, Kabupaten Bolaang Mongondow Timur',
  },
  {
    'province': 'Sulawesi Utara',
    'city': 'Kota Manado',
    'label': 'Sulawesi Utara, Kota Manado',
  },
  {
    'province': 'Sulawesi Utara',
    'city': 'Kota Bitung',
    'label': 'Sulawesi Utara, Kota Bitung',
  },
  {
    'province': 'Sulawesi Utara',
    'city': 'Kota Tomohon',
    'label': 'Sulawesi Utara, Kota Tomohon',
  },
  {
    'province': 'Sulawesi Utara',
    'city': 'Kota Kotamobagu',
    'label': 'Sulawesi Utara, Kota Kotamobagu',
  },
  {
    'province': 'Sulawesi Tengah',
    'city': 'Kabupaten Banggai Kepulauan',
    'label': 'Sulawesi Tengah, Kabupaten Banggai Kepulauan',
  },
  {
    'province': 'Sulawesi Tengah',
    'city': 'Kabupaten Banggai',
    'label': 'Sulawesi Tengah, Kabupaten Banggai',
  },
  {
    'province': 'Sulawesi Tengah',
    'city': 'Kabupaten Morowali',
    'label': 'Sulawesi Tengah, Kabupaten Morowali',
  },
  {
    'province': 'Sulawesi Tengah',
    'city': 'Kabupaten Poso',
    'label': 'Sulawesi Tengah, Kabupaten Poso',
  },
  {
    'province': 'Sulawesi Tengah',
    'city': 'Kabupaten Donggala',
    'label': 'Sulawesi Tengah, Kabupaten Donggala',
  },
  {
    'province': 'Sulawesi Tengah',
    'city': 'Kabupaten Toli-toli',
    'label': 'Sulawesi Tengah, Kabupaten Toli-toli',
  },
  {
    'province': 'Sulawesi Tengah',
    'city': 'Kabupaten Buol',
    'label': 'Sulawesi Tengah, Kabupaten Buol',
  },
  {
    'province': 'Sulawesi Tengah',
    'city': 'Kabupaten Parigi Moutong',
    'label': 'Sulawesi Tengah, Kabupaten Parigi Moutong',
  },
  {
    'province': 'Sulawesi Tengah',
    'city': 'Kabupaten Tojo Una-una',
    'label': 'Sulawesi Tengah, Kabupaten Tojo Una-una',
  },
  {
    'province': 'Sulawesi Tengah',
    'city': 'Kabupaten Sigi',
    'label': 'Sulawesi Tengah, Kabupaten Sigi',
  },
  {
    'province': 'Sulawesi Tengah',
    'city': 'Kabupaten Banggai Laut',
    'label': 'Sulawesi Tengah, Kabupaten Banggai Laut',
  },
  {
    'province': 'Sulawesi Tengah',
    'city': 'Kabupaten Morowali Utara',
    'label': 'Sulawesi Tengah, Kabupaten Morowali Utara',
  },
  {
    'province': 'Sulawesi Tengah',
    'city': 'Kota Palu',
    'label': 'Sulawesi Tengah, Kota Palu',
  },
  {
    'province': 'Sulawesi Selatan',
    'city': 'Kabupaten Kepulauan Selayar',
    'label': 'Sulawesi Selatan, Kabupaten Kepulauan Selayar',
  },
  {
    'province': 'Sulawesi Selatan',
    'city': 'Kabupaten Bulukumba',
    'label': 'Sulawesi Selatan, Kabupaten Bulukumba',
  },
  {
    'province': 'Sulawesi Selatan',
    'city': 'Kabupaten Bantaeng',
    'label': 'Sulawesi Selatan, Kabupaten Bantaeng',
  },
  {
    'province': 'Sulawesi Selatan',
    'city': 'Kabupaten Jeneponto',
    'label': 'Sulawesi Selatan, Kabupaten Jeneponto',
  },
  {
    'province': 'Sulawesi Selatan',
    'city': 'Kabupaten Takalar',
    'label': 'Sulawesi Selatan, Kabupaten Takalar',
  },
  {
    'province': 'Sulawesi Selatan',
    'city': 'Kabupaten Gowa',
    'label': 'Sulawesi Selatan, Kabupaten Gowa',
  },
  {
    'province': 'Sulawesi Selatan',
    'city': 'Kabupaten Sinjai',
    'label': 'Sulawesi Selatan, Kabupaten Sinjai',
  },
  {
    'province': 'Sulawesi Selatan',
    'city': 'Kabupaten Maros',
    'label': 'Sulawesi Selatan, Kabupaten Maros',
  },
  {
    'province': 'Sulawesi Selatan',
    'city': 'Kabupaten Pangkajene Dan Kepulauan',
    'label': 'Sulawesi Selatan, Kabupaten Pangkajene Dan Kepulauan',
  },
  {
    'province': 'Sulawesi Selatan',
    'city': 'Kabupaten Barru',
    'label': 'Sulawesi Selatan, Kabupaten Barru',
  },
  {
    'province': 'Sulawesi Selatan',
    'city': 'Kabupaten Bone',
    'label': 'Sulawesi Selatan, Kabupaten Bone',
  },
  {
    'province': 'Sulawesi Selatan',
    'city': 'Kabupaten Soppeng',
    'label': 'Sulawesi Selatan, Kabupaten Soppeng',
  },
  {
    'province': 'Sulawesi Selatan',
    'city': 'Kabupaten Wajo',
    'label': 'Sulawesi Selatan, Kabupaten Wajo',
  },
  {
    'province': 'Sulawesi Selatan',
    'city': 'Kabupaten Sidenreng Rappang',
    'label': 'Sulawesi Selatan, Kabupaten Sidenreng Rappang',
  },
  {
    'province': 'Sulawesi Selatan',
    'city': 'Kabupaten Pinrang',
    'label': 'Sulawesi Selatan, Kabupaten Pinrang',
  },
  {
    'province': 'Sulawesi Selatan',
    'city': 'Kabupaten Enrekang',
    'label': 'Sulawesi Selatan, Kabupaten Enrekang',
  },
  {
    'province': 'Sulawesi Selatan',
    'city': 'Kabupaten Luwu',
    'label': 'Sulawesi Selatan, Kabupaten Luwu',
  },
  {
    'province': 'Sulawesi Selatan',
    'city': 'Kabupaten Tana Toraja',
    'label': 'Sulawesi Selatan, Kabupaten Tana Toraja',
  },
  {
    'province': 'Sulawesi Selatan',
    'city': 'Kabupaten Luwu Utara',
    'label': 'Sulawesi Selatan, Kabupaten Luwu Utara',
  },
  {
    'province': 'Sulawesi Selatan',
    'city': 'Kabupaten Luwu Timur',
    'label': 'Sulawesi Selatan, Kabupaten Luwu Timur',
  },
  {
    'province': 'Sulawesi Selatan',
    'city': 'Kabupaten Toraja Utara',
    'label': 'Sulawesi Selatan, Kabupaten Toraja Utara',
  },
  {
    'province': 'Sulawesi Selatan',
    'city': 'Kota Makassar',
    'label': 'Sulawesi Selatan, Kota Makassar',
  },
  {
    'province': 'Sulawesi Selatan',
    'city': 'Kota Parepare',
    'label': 'Sulawesi Selatan, Kota Parepare',
  },
  {
    'province': 'Sulawesi Selatan',
    'city': 'Kota Palopo',
    'label': 'Sulawesi Selatan, Kota Palopo',
  },
  {
    'province': 'Sulawesi Tenggara',
    'city': 'Kabupaten Buton',
    'label': 'Sulawesi Tenggara, Kabupaten Buton',
  },
  {
    'province': 'Sulawesi Tenggara',
    'city': 'Kabupaten Muna',
    'label': 'Sulawesi Tenggara, Kabupaten Muna',
  },
  {
    'province': 'Sulawesi Tenggara',
    'city': 'Kabupaten Konawe',
    'label': 'Sulawesi Tenggara, Kabupaten Konawe',
  },
  {
    'province': 'Sulawesi Tenggara',
    'city': 'Kabupaten Kolaka',
    'label': 'Sulawesi Tenggara, Kabupaten Kolaka',
  },
  {
    'province': 'Sulawesi Tenggara',
    'city': 'Kabupaten Konawe Selatan',
    'label': 'Sulawesi Tenggara, Kabupaten Konawe Selatan',
  },
  {
    'province': 'Sulawesi Tenggara',
    'city': 'Kabupaten Bombana',
    'label': 'Sulawesi Tenggara, Kabupaten Bombana',
  },
  {
    'province': 'Sulawesi Tenggara',
    'city': 'Kabupaten Wakatobi',
    'label': 'Sulawesi Tenggara, Kabupaten Wakatobi',
  },
  {
    'province': 'Sulawesi Tenggara',
    'city': 'Kabupaten Kolaka Utara',
    'label': 'Sulawesi Tenggara, Kabupaten Kolaka Utara',
  },
  {
    'province': 'Sulawesi Tenggara',
    'city': 'Kabupaten Buton Utara',
    'label': 'Sulawesi Tenggara, Kabupaten Buton Utara',
  },
  {
    'province': 'Sulawesi Tenggara',
    'city': 'Kabupaten Konawe Utara',
    'label': 'Sulawesi Tenggara, Kabupaten Konawe Utara',
  },
  {
    'province': 'Sulawesi Tenggara',
    'city': 'Kabupaten Kolaka Timur',
    'label': 'Sulawesi Tenggara, Kabupaten Kolaka Timur',
  },
  {
    'province': 'Sulawesi Tenggara',
    'city': 'Kabupaten Konawe Kepulauan',
    'label': 'Sulawesi Tenggara, Kabupaten Konawe Kepulauan',
  },
  {
    'province': 'Sulawesi Tenggara',
    'city': 'Kabupaten Muna Barat',
    'label': 'Sulawesi Tenggara, Kabupaten Muna Barat',
  },
  {
    'province': 'Sulawesi Tenggara',
    'city': 'Kabupaten Buton Tengah',
    'label': 'Sulawesi Tenggara, Kabupaten Buton Tengah',
  },
  {
    'province': 'Sulawesi Tenggara',
    'city': 'Kabupaten Buton Selatan',
    'label': 'Sulawesi Tenggara, Kabupaten Buton Selatan',
  },
  {
    'province': 'Sulawesi Tenggara',
    'city': 'Kota Kendari',
    'label': 'Sulawesi Tenggara, Kota Kendari',
  },
  {
    'province': 'Sulawesi Tenggara',
    'city': 'Kota Baubau',
    'label': 'Sulawesi Tenggara, Kota Baubau',
  },
  {
    'province': 'Gorontalo',
    'city': 'Kabupaten Boalemo',
    'label': 'Gorontalo, Kabupaten Boalemo',
  },
  {
    'province': 'Gorontalo',
    'city': 'Kabupaten Gorontalo',
    'label': 'Gorontalo, Kabupaten Gorontalo',
  },
  {
    'province': 'Gorontalo',
    'city': 'Kabupaten Pohuwato',
    'label': 'Gorontalo, Kabupaten Pohuwato',
  },
  {
    'province': 'Gorontalo',
    'city': 'Kabupaten Bone Bolango',
    'label': 'Gorontalo, Kabupaten Bone Bolango',
  },
  {
    'province': 'Gorontalo',
    'city': 'Kabupaten Gorontalo Utara',
    'label': 'Gorontalo, Kabupaten Gorontalo Utara',
  },
  {
    'province': 'Gorontalo',
    'city': 'Kota Gorontalo',
    'label': 'Gorontalo, Kota Gorontalo',
  },
  {
    'province': 'Sulawesi Barat',
    'city': 'Kabupaten Majene',
    'label': 'Sulawesi Barat, Kabupaten Majene',
  },
  {
    'province': 'Sulawesi Barat',
    'city': 'Kabupaten Polewali Mandar',
    'label': 'Sulawesi Barat, Kabupaten Polewali Mandar',
  },
  {
    'province': 'Sulawesi Barat',
    'city': 'Kabupaten Mamasa',
    'label': 'Sulawesi Barat, Kabupaten Mamasa',
  },
  {
    'province': 'Sulawesi Barat',
    'city': 'Kabupaten Mamuju',
    'label': 'Sulawesi Barat, Kabupaten Mamuju',
  },
  {
    'province': 'Sulawesi Barat',
    'city': 'Kabupaten Mamuju Utara',
    'label': 'Sulawesi Barat, Kabupaten Mamuju Utara',
  },
  {
    'province': 'Sulawesi Barat',
    'city': 'Kabupaten Mamuju Tengah',
    'label': 'Sulawesi Barat, Kabupaten Mamuju Tengah',
  },
  {
    'province': 'Maluku',
    'city': 'Kabupaten Maluku Tenggara Barat',
    'label': 'Maluku, Kabupaten Maluku Tenggara Barat',
  },
  {
    'province': 'Maluku',
    'city': 'Kabupaten Maluku Tenggara',
    'label': 'Maluku, Kabupaten Maluku Tenggara',
  },
  {
    'province': 'Maluku',
    'city': 'Kabupaten Maluku Tengah',
    'label': 'Maluku, Kabupaten Maluku Tengah',
  },
  {
    'province': 'Maluku',
    'city': 'Kabupaten Buru',
    'label': 'Maluku, Kabupaten Buru',
  },
  {
    'province': 'Maluku',
    'city': 'Kabupaten Kepulauan Aru',
    'label': 'Maluku, Kabupaten Kepulauan Aru',
  },
  {
    'province': 'Maluku',
    'city': 'Kabupaten Seram Bagian Barat',
    'label': 'Maluku, Kabupaten Seram Bagian Barat',
  },
  {
    'province': 'Maluku',
    'city': 'Kabupaten Seram Bagian Timur',
    'label': 'Maluku, Kabupaten Seram Bagian Timur',
  },
  {
    'province': 'Maluku',
    'city': 'Kabupaten Maluku Barat Daya',
    'label': 'Maluku, Kabupaten Maluku Barat Daya',
  },
  {
    'province': 'Maluku',
    'city': 'Kabupaten Buru Selatan',
    'label': 'Maluku, Kabupaten Buru Selatan',
  },
  {'province': 'Maluku', 'city': 'Kota Ambon', 'label': 'Maluku, Kota Ambon'},
  {'province': 'Maluku', 'city': 'Kota Tual', 'label': 'Maluku, Kota Tual'},
  {
    'province': 'Maluku Utara',
    'city': 'Kabupaten Halmahera Barat',
    'label': 'Maluku Utara, Kabupaten Halmahera Barat',
  },
  {
    'province': 'Maluku Utara',
    'city': 'Kabupaten Halmahera Tengah',
    'label': 'Maluku Utara, Kabupaten Halmahera Tengah',
  },
  {
    'province': 'Maluku Utara',
    'city': 'Kabupaten Kepulauan Sula',
    'label': 'Maluku Utara, Kabupaten Kepulauan Sula',
  },
  {
    'province': 'Maluku Utara',
    'city': 'Kabupaten Halmahera Selatan',
    'label': 'Maluku Utara, Kabupaten Halmahera Selatan',
  },
  {
    'province': 'Maluku Utara',
    'city': 'Kabupaten Halmahera Utara',
    'label': 'Maluku Utara, Kabupaten Halmahera Utara',
  },
  {
    'province': 'Maluku Utara',
    'city': 'Kabupaten Halmahera Timur',
    'label': 'Maluku Utara, Kabupaten Halmahera Timur',
  },
  {
    'province': 'Maluku Utara',
    'city': 'Kabupaten Pulau Morotai',
    'label': 'Maluku Utara, Kabupaten Pulau Morotai',
  },
  {
    'province': 'Maluku Utara',
    'city': 'Kabupaten Pulau Taliabu',
    'label': 'Maluku Utara, Kabupaten Pulau Taliabu',
  },
  {
    'province': 'Maluku Utara',
    'city': 'Kota Ternate',
    'label': 'Maluku Utara, Kota Ternate',
  },
  {
    'province': 'Maluku Utara',
    'city': 'Kota Tidore Kepulauan',
    'label': 'Maluku Utara, Kota Tidore Kepulauan',
  },
  {
    'province': 'Papua Barat',
    'city': 'Kabupaten Fakfak',
    'label': 'Papua Barat, Kabupaten Fakfak',
  },
  {
    'province': 'Papua Barat',
    'city': 'Kabupaten Kaimana',
    'label': 'Papua Barat, Kabupaten Kaimana',
  },
  {
    'province': 'Papua Barat',
    'city': 'Kabupaten Teluk Wondama',
    'label': 'Papua Barat, Kabupaten Teluk Wondama',
  },
  {
    'province': 'Papua Barat',
    'city': 'Kabupaten Teluk Bintuni',
    'label': 'Papua Barat, Kabupaten Teluk Bintuni',
  },
  {
    'province': 'Papua Barat',
    'city': 'Kabupaten Manokwari',
    'label': 'Papua Barat, Kabupaten Manokwari',
  },
  {
    'province': 'Papua Barat',
    'city': 'Kabupaten Sorong Selatan',
    'label': 'Papua Barat, Kabupaten Sorong Selatan',
  },
  {
    'province': 'Papua Barat',
    'city': 'Kabupaten Sorong',
    'label': 'Papua Barat, Kabupaten Sorong',
  },
  {
    'province': 'Papua Barat',
    'city': 'Kabupaten Raja Ampat',
    'label': 'Papua Barat, Kabupaten Raja Ampat',
  },
  {
    'province': 'Papua Barat',
    'city': 'Kabupaten Tambrauw',
    'label': 'Papua Barat, Kabupaten Tambrauw',
  },
  {
    'province': 'Papua Barat',
    'city': 'Kabupaten Maybrat',
    'label': 'Papua Barat, Kabupaten Maybrat',
  },
  {
    'province': 'Papua Barat',
    'city': 'Kabupaten Manokwari Selatan',
    'label': 'Papua Barat, Kabupaten Manokwari Selatan',
  },
  {
    'province': 'Papua Barat',
    'city': 'Kabupaten Pegunungan Arfak',
    'label': 'Papua Barat, Kabupaten Pegunungan Arfak',
  },
  {
    'province': 'Papua Barat',
    'city': 'Kota Sorong',
    'label': 'Papua Barat, Kota Sorong',
  },
  {
    'province': 'Papua',
    'city': 'Kabupaten Merauke',
    'label': 'Papua, Kabupaten Merauke',
  },
  {
    'province': 'Papua',
    'city': 'Kabupaten Jayawijaya',
    'label': 'Papua, Kabupaten Jayawijaya',
  },
  {
    'province': 'Papua',
    'city': 'Kabupaten Jayapura',
    'label': 'Papua, Kabupaten Jayapura',
  },
  {
    'province': 'Papua',
    'city': 'Kabupaten Nabire',
    'label': 'Papua, Kabupaten Nabire',
  },
  {
    'province': 'Papua',
    'city': 'Kabupaten Kepulauan Yapen',
    'label': 'Papua, Kabupaten Kepulauan Yapen',
  },
  {
    'province': 'Papua',
    'city': 'Kabupaten Biak Numfor',
    'label': 'Papua, Kabupaten Biak Numfor',
  },
  {
    'province': 'Papua',
    'city': 'Kabupaten Paniai',
    'label': 'Papua, Kabupaten Paniai',
  },
  {
    'province': 'Papua',
    'city': 'Kabupaten Puncak Jaya',
    'label': 'Papua, Kabupaten Puncak Jaya',
  },
  {
    'province': 'Papua',
    'city': 'Kabupaten Mimika',
    'label': 'Papua, Kabupaten Mimika',
  },
  {
    'province': 'Papua',
    'city': 'Kabupaten Boven Digoel',
    'label': 'Papua, Kabupaten Boven Digoel',
  },
  {
    'province': 'Papua',
    'city': 'Kabupaten Mappi',
    'label': 'Papua, Kabupaten Mappi',
  },
  {
    'province': 'Papua',
    'city': 'Kabupaten Asmat',
    'label': 'Papua, Kabupaten Asmat',
  },
  {
    'province': 'Papua',
    'city': 'Kabupaten Yahukimo',
    'label': 'Papua, Kabupaten Yahukimo',
  },
  {
    'province': 'Papua',
    'city': 'Kabupaten Pegunungan Bintang',
    'label': 'Papua, Kabupaten Pegunungan Bintang',
  },
  {
    'province': 'Papua',
    'city': 'Kabupaten Tolikara',
    'label': 'Papua, Kabupaten Tolikara',
  },
  {
    'province': 'Papua',
    'city': 'Kabupaten Sarmi',
    'label': 'Papua, Kabupaten Sarmi',
  },
  {
    'province': 'Papua',
    'city': 'Kabupaten Keerom',
    'label': 'Papua, Kabupaten Keerom',
  },
  {
    'province': 'Papua',
    'city': 'Kabupaten Waropen',
    'label': 'Papua, Kabupaten Waropen',
  },
  {
    'province': 'Papua',
    'city': 'Kabupaten Supiori',
    'label': 'Papua, Kabupaten Supiori',
  },
  {
    'province': 'Papua',
    'city': 'Kabupaten Mamberamo Raya',
    'label': 'Papua, Kabupaten Mamberamo Raya',
  },
  {
    'province': 'Papua',
    'city': 'Kabupaten Nduga',
    'label': 'Papua, Kabupaten Nduga',
  },
  {
    'province': 'Papua',
    'city': 'Kabupaten Lanny Jaya',
    'label': 'Papua, Kabupaten Lanny Jaya',
  },
  {
    'province': 'Papua',
    'city': 'Kabupaten Mamberamo Tengah',
    'label': 'Papua, Kabupaten Mamberamo Tengah',
  },
  {
    'province': 'Papua',
    'city': 'Kabupaten Yalimo',
    'label': 'Papua, Kabupaten Yalimo',
  },
  {
    'province': 'Papua',
    'city': 'Kabupaten Puncak',
    'label': 'Papua, Kabupaten Puncak',
  },
  {
    'province': 'Papua',
    'city': 'Kabupaten Dogiyai',
    'label': 'Papua, Kabupaten Dogiyai',
  },
  {
    'province': 'Papua',
    'city': 'Kabupaten Intan Jaya',
    'label': 'Papua, Kabupaten Intan Jaya',
  },
  {
    'province': 'Papua',
    'city': 'Kabupaten Deiyai',
    'label': 'Papua, Kabupaten Deiyai',
  },
  {
    'province': 'Papua',
    'city': 'Kota Jayapura',
    'label': 'Papua, Kota Jayapura',
  },
];
